@startuml development
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

Boundary(vpc, "project-name.com.br", "Ambiente na núvem, protegido") {
    Container(branch, "Branch", "Branch onde será implementado a feature")
    Container(image, "Docker image", "Aplicação que executa o código de uma branch")
    Container(docker, "Docker container solution", "Permite executar a aplicação pegando chaves, endereços, usuários e senhas do ambiente e carregando no startup")
}

Rel(branch, image, "Gera")
Rel(image, docker, "Executa")
@enduml